### ISSUE TITLE
Implement MVVM

### ISSUE THREAD

**Issue by zluzunov** [HakuTeam/SoundWizard#1]
Implement what you learned from the MVVM pattern in our project.
Use the namespace "SoundWizard";

**Comment by AlisaTerzieva** [comment]
I have created the basic structure of MVVM and migrated part of the business logic to the ViewModel. Currently I am trying to deal with the commands from the View.

e51a38d82b0d37aca158402204a3aff38f3bc24c

**Comment by zluzunov** [comment]
SongViewModel added to the project:
See: ac4d067734e172ea8775e57a09b6a0abbe395147

**Comment by zluzunov** [comment]
Most buttons separated - now work with ICommand; 
Most logic moved to SongViewModel (MainViewModel);
See commits from:
1ae92524dc6e99d19fd17cdbba5d491fe132cb05
To:
b23e367e61fc30b21fcf382400f743577ae15001
