### ISSUE TITLE
Playlist: Forward, Rewind buttons - to loop songs

### ISSUE THREAD

**Issue by zluzunov** [HakuTeam/SoundWizard#11]
When forward click reaches the end/beginning of the list to jump to the other side of the list;

**Comment by dhtveso** [comment]
MediaElement.Position += TimeSpan.FromSeconds(10);
      if (MediaElement.Position >= MediaElement.NaturalDuration.TimeSpan)
      {
        MediaElement.Position -= TimeSpan.FromMilliseconds(100);
      }

code for forward

**Comment by zluzunov** [comment]
See RepeatButton Control @dhtveso 

by @AlisaTerzieva

**Comment by dhtveso** [comment]
Ready now repeat playlist. 0b14a90
