### ISSUE TITLE
Study MVVM

### ISSUE THREAD

**Issue by zluzunov** [HakuTeam/SoundWizard#5]
Read about MVVM, help other implement their code according to this pattern.
Example materials:

- [Pluralsight 1](https://app.pluralsight.com/library/courses/practical-mvvm/table-of-contents)
- [Pluralsight 2](https://app.pluralsight.com/library/courses/wpf-mvvm-in-depth/table-of-contents)

Related to:
#1

**Comment by AlisaTerzieva** [comment]
I have learned the basic concepts of MVVM. I am currently studiyng the commands and processes and ViewModel communication.

**Comment by zluzunov** [comment]
More useful links that I used:
[MVVM Light](https://app.pluralsight.com/library/courses/mvvm-light-toolkit-fundamentals/table-of-contents)
[WPF/MVVM Quick Start Tutorial](https://www.codeproject.com/articles/165368/wpf-mvvm-quick-start-tutorial)

**Comment by zluzunov** [comment]
More useful links that I used:
[MVVM Light](https://app.pluralsight.com/library/courses/mvvm-light-toolkit-fundamentals/table-of-contents)
[WPF/MVVM Quick Start Tutorial](https://www.codeproject.com/articles/165368/wpf-mvvm-quick-start-tutorial)

**Comment by zluzunov** [comment]
We know enough to make an initial implementation of MVVM;
