### ISSUE TITLE
Playlist show song title and duration

### ISSUE THREAD

**Issue by zluzunov** [HakuTeam/SoundWizard#7]

**Comment by badbutcher** [comment]
Done

**Comment by zluzunov** [comment]
Implemented duration with [Microsoft.WindowsAPICodePack.Shell](https://www.nuget.org/packages/Microsoft.WindowsAPICodePack.Shell/)
[See stackoverflow answer](https://stackoverflow.com/questions/18602652/getting-mp3-file-length?answertab=votes#tab-top)

commits:
[0870d5ef](https://github.com/HakuTeam/SoundWizard/commit/0870d5efa7bc54c35c631e76261bde661909647a)
